name = "PassivbotJL"
uuid = "12345678-1234-1234-1234-123456789012"
authors = ["Your Name <your.email@example.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
GR = "0.73.18"
HTTP = "1.10.19"
LoggingExtras = "1.2.0"
MbedTLS = "1.1.9"
Plots = "1.41.1"
SHA = "0.7.0"
StatsBase = "0.34.8"
WebSockets = "1.6.0"
YAML = "0.4.16"
julia = "1.6"
